import type { Metadata } from 'next'

import { RootProvider } from '@partials/providers/RootProvider'

import { type TWrapperWithChildrenType } from '@core/types/common/wrapper-with-children'
import { inter } from '@core/utils/fonts'

import '../styles/globals.css'

export const metadata: Metadata = {
    title: 'Advanced Next.js Starter Kit',
    description: 'Generated by GetWrecked'
}

const RootLayout = ({ children }: TWrapperWithChildrenType) => {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <RootProvider>{children}</RootProvider>
            </body>
        </html>
    )
}

export default RootLayout
