import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { RootProvider } from '@partials/providers/RootProvider'

import { type TWrapperWithChildrenType } from '@core/types/common/wrapper-with-children'

import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

const RootLayout = ({ children }: TWrapperWithChildrenType) => {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <RootProvider>{children}</RootProvider>
            </body>
        </html>
    )
}

export default RootLayout
